services:
  app:
    image: todo-front-dev
    build:
      context: ./todo-frontend # The context will pick this directory as the "build context"
      dockerfile: ./todo-frontend/dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./todo-frontend:/usr/src/app # The path can be relative, so ./ is enough to say "the same location as the docker-compose.yml"
    ports:
      - 3000:3000
    container_name: hello-front-dev # This will name the container hello-front-dev

  server:
    image: todo-backend-dev
    volumes:
      - ./todo-backend:/usr/src/app
    ports:
      - 7000:7000
    container_name: server
    environment:
      - REDIS_URL=redis://host.docker.internal:6379
      - MONGO_URL=mongodb://the_username:the_password@host.docker.internal:3456/the_database

  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    container_name: reverse-proxy
    depends_on:
      - app # wait for the frontend container to be started
      - server # wait for the frontend container to be started
