version: '3.8'

services:
  server:
    image: todo-backend-dev
    volumes:
      - ./:/usr/src/app
    ports:
      - 7000:7000
    container_name: todo-dev-server
    environment: 
      - REDIS_URL=redis://host.docker.internal:6379
      - MONGO_URL=mongodb://the_username:the_password@host.docker.internal:3456/the_database


  
